theme: "minima"

title: Ali's Blog
author: Shahnawaz ali
description: >
  An effort towards Simplifying concepts

timezone: GMT/BST # GitHub uses UTC.
future: false

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: saalis.uk@@mail.com
twitter_username: shahnawaz_mbd
github_username: shahnawazkcl
linkedin_username: shahnawaz-ali-jmi
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################


rss: rss
home_post_limit: 7
kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
